# Working with `TENSORS`

Return to the [castle](https://github.com/Nkluge-correa/teeny-tiny_castle).

**Tensors are a specialized data structure that are very similar to arrays and matrices. In mathematics, a _tensor_ is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space. Objects that tensors may map between include vectors and scalars, and even other tensors.**

![tensors](https://images.nvidia.com/aem-dam/Solutions/Data-Center/tesla-t4/Turing-Tensor-Core_30fps_FINAL_736x414.gif)


In [1]:
import torch
import numpy as np


**Tensors can be created from:**

- _directly from data._
- _from NumPy arrays._
- _form another Tensor._


In [8]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(type(data), type(x_data))
display(x_data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(type(np_array), type(x_np))
display(x_np)


<class 'list'> <class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4]])

<class 'numpy.ndarray'> <class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

- `torch.ones_like`: _creates a tensor of 'ones' that retains the properties of some reference._
- `torch.rand_like`: _creates a tensor of random numbers that retains the properties of some reference._


In [6]:
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

# dtype=torch.float overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7862, 0.0438],
        [0.4974, 0.1137]]) 



**Bellow, the variable `shape` is a tuple of tensor dimensions. It determines the dimensionality of the output tensor.**


In [53]:
shape = (3, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')


Random Tensor: 
 tensor([[0.7326, 0.1595, 0.1310],
        [0.3994, 0.3787, 0.3583],
        [0.3493, 0.1248, 0.4439]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**Like vectors and matrices, you can calculate arithmetic operations with tensors.**


In [54]:
print(
    f'Dot product of rand_tensor with itself: \n {np.dot(rand_tensor, rand_tensor)} \n')

# rand_tensor.mul(zeros_tensor)
print(
    f'The element-wise product of rand_tensor with zeros_tensor: \n {rand_tensor * zeros_tensor} \n')

print(f'rand_tensor plus ones_tensor: \n {rand_tensor + ones_tensor} \n')

# ones_tensor.matmul(ones_tensor.T) is equivalent
print(
    f'Matrix multiplication between ones_tensor with itself: \n {ones_tensor @ ones_tensor.T} \n')

print(
    f'Summation of all elements in ones_tensor: \n {ones_tensor.sum().item()} \n')

print(
    f'Adding a constant to all elements in rand_tensor: \n {rand_tensor.add_(3)} \n')


Dot product of rand_tensor with itself: 
 [[0.6461566  0.19364569 0.21128307]
 [0.5689914  0.2518838  0.34704387]
 [0.46077016 0.15842146 0.28752598]] 

The element-wise product of rand_tensor with zeros_tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

rand_tensor plus ones_tensor: 
 tensor([[1.7326, 1.1595, 1.1310],
        [1.3994, 1.3787, 1.3583],
        [1.3493, 1.1248, 1.4439]]) 

Matrix multiplication between ones_tensor with itself: 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) 

Summation of all elements in ones_tensor: 
 9.0 

Adding a constant to all elements in rand_tensor: 
 tensor([[3.7326, 3.1595, 3.1310],
        [3.3994, 3.3787, 3.3583],
        [3.3493, 3.1248, 3.4439]]) 



**Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).**


**Tensor attributes describe their shape, datatype, and the device on which they are stored.**

- _By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method (after checking for GPU availability)._


In [28]:
print(f'Shape of tensor: {rand_tensor.shape}\n')
print(f'Datatype of tensor: {rand_tensor.dtype}\n')
print(f'Device tensor is stored on: {rand_tensor.device}\n')
if torch.cuda.is_available():
    gpu_rand_tensor = rand_tensor.to("cuda")
print(f'Device tensor is stored on: {gpu_rand_tensor.device}')


Shape of tensor: torch.Size([5, 5])

Datatype of tensor: torch.float32

Device tensor is stored on: cpu

Device tensor is stored on: cuda:0


**You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also `torch.stack`, another tensor joining op that is subtly different from `torch.cat`.**


In [33]:
join_tensor = torch.cat([rand_tensor, ones_tensor, zeros_tensor], dim=0)
print(f'Concatenated tensors: \n{join_tensor}\n')
join_tensor = torch.stack([rand_tensor, ones_tensor, zeros_tensor], dim=0)
print(f'Staked tensors: \n{join_tensor}\n')


Concatenated tensors: 
tensor([[0.5219, 0.0954, 0.3577, 0.8004, 0.5817],
        [0.5285, 0.5968, 0.7817, 0.4855, 0.1202],
        [0.2983, 0.6091, 0.4962, 0.1911, 0.0287],
        [0.4701, 0.5074, 0.6865, 0.7861, 0.5892],
        [0.4008, 0.0280, 0.1837, 0.8371, 0.7738],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

Staked tensors: 
tensor([[[0.5219, 0.0954, 0.3577, 0.8004, 0.5817],
         [0.5285, 0.5968, 0.7817, 0.4855, 0.1202],
         [0.2983, 0.6091, 0.4962, 0.1911, 0.0287],
         [0.4701, 0.5074, 0.6865, 0.7861, 0.5892],
    

**For a full and comprehensive tutorial on tensors, visit the [Introduction to Tensors](https://www.tensorflow.org/guide/tensor) tutorial.**

---

Return to the [castle](https://github.com/Nkluge-correa/teeny-tiny_castle).
